extends@: default

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            # Add subtitle to the content section.
            columns:
              type: columns
              fields:
                column1:
                  type: column
                  fields:
                    header.subtitle:
                      type: text
                      label: Subtitle
                      help: A subtitle to display sometimes under the title of a page.
                      style: fancy
                column2: # Blank to make the subtitle a bit smaller and less lonely.
                  type: column
                  fields:
        hypertext:
          type: tab
          title: Hypertext
          fields:
            columns:
              type: columns
              fields:
                overrides_column:
                  type: column
                  fields:
                    overrides_title:
                      type: section
                      title: JS/CSS Overrides
                      underline: true                      
                    header.allowCSS:
                      type: select
                      label: Allow CSS Override
                      help: Allow CSS only for this page, overriding any global settings.
                      classes: fancy
                      options:
                        default: Use global setting
                        enabled: Allow CSS
                        disabled: Block CSS
                    header.allowJS:
                      type: select
                      label: Allow JS Override
                      help: Allow JS only for this page, overriding any global settings.
                      classes: fancy
                      options:
                        default: Use global setting
                        enabled: Allow JS
                        disabled: Block JS
                    header.customCSS:
                      type: textarea
                      label: Custom CSS
                      size: large
                      help: Add your page-specific, custom CSS rules here.
                      placeholder: "e.g. table { font-family: Courier }"
                content_column:
                  type: column
                  title: Extra Content & Metadata
                  fields:
                    content:
                      type: section
                      title: Extra Content
                      underline: true
                    header.subtitle:
                      type: text
                      label: Subtitle
                      help: A subtitle to display sometimes under the title of a page.
                      placeholder: A snarky sub-title elaborating on this page's title.
                      style: fancy

                    header.header_image:
                      type: toggle
                      toggleable: true
                      label: Display Header Image
                      help: Enabled displaying of a header image
                      highlight: 1
                      options:
                        1: Enabled
                        0: Disabled
                    header.header_image_file:
                      type: text
                      toggleable: true
                      label: Image File
                      help: Image filename that exists in the page folder. If not provided, and header image is enabled, Hypertext will use the first image found.
                      placeholder: myimage.jpg

                    header.summary.delimiter:
                      type: text
                      help: A delimiter to use between the page summary and the rest of its contents. Anything above this delimiter will be used as the page summary, shown in any collections this page is a part of.
                      toggleable: true
                      label: Summary delimiter
                      classes: large
                      placeholder: ===
                    header.summary.length:
                      type: text
                      help: The amount of text to take from the beginning of this page *if* you don't use the summary delimiter.
                      toggleable: true
                      label: Summary Length
                      classes: large
                      placeholder: 300
                      validate:
                        type: int
                        min: 1
                    
                    